### ISSUE TITLE
Create move method for enemies

### ISSUE THREAD

**Issue by RAWeber** [cpe305/fall2016-project-RAWeber#5]
Edit the enemy class to:
1) Have an int x and y coordinates
2) Have a starting spawn PathSquare
3) Move towards the PathSquare's getCenteredX() and getCenteredY() by the enemies speed
4) Once it has reached the center, set new destination to the PathSquare's getNextSquare()
5) loop until getNextSquare() is null

*Because you most likely wont be able to get my project into eclipse, don't worry about testing

**Comment by mdavis60** [comment]
check out the move method I made.
